const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');const D=read('DESIGN.md'),E=read('EXPERIENCE.md');let errors=[],results=[];
const keys=new Set(),stack=[];for(const line of D.split('---')[1].split('\n')){const m=line.match(/^( *)([\w-]+):/);if(!m)continue;const level=m[1].length;while(stack.length&&stack.at(-1).level>=level)stack.pop();stack.push({level,key:m[2]});keys.add(stack.map(x=>x.key).join('.'));}
let n=0;for(const s of [D,E])for(const m of s.matchAll(/\{((?:colors|typography|rounded|spacing|components)\.[\w.-]+)\}/g)){n++;if(!keys.has(m[1]))errors.push('Unknown token '+m[1]);}results.push(n+' token references resolve');
let links=0;for(const [name,s]of [['DESIGN.md',D],['EXPERIENCE.md',E]]){for(const m of s.matchAll(/\]\(([^)]+)\)/g)){const u=m[1].split('#')[0];if(!u||/^(https?:|mailto:)/.test(u))continue;links++;if(!fs.existsSync(path.resolve(root,u)))errors.push(name+' missing link '+u);}for(const m of s.split('---')[1].matchAll(/^\s*- (\.\.\/.*)$/gm))if(!fs.existsSync(path.resolve(root,m[1].trim())))errors.push('Missing source '+m[1]);}results.push(links+' local spine links and all source paths resolve');
function catalog(s,heading){return s.split(heading+'\n')[1].split('\n## ')[0].split('\n').filter(l=>/^\| [^|]+ \|/.test(l)).map(l=>l.split('|')[1].trim()).filter(l=>!['Component','Name'].includes(l));}
const dc=catalog(D,'## Components'),ec=catalog(E,'## Component Patterns');for(const x of dc)if(!ec.includes(x))errors.push('Missing behavior component '+x);for(const x of ec)if(!dc.includes(x))errors.push('Missing visual component '+x);results.push('Component catalogs checked ('+dc.length+'/'+ec.length+')');
for(const file of fs.readdirSync(path.join(root,'mockups'))){if(!file.endsWith('.html'))continue;const s=read('mockups/'+file),ids=[...s.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);if(new Set(ids).size!==ids.length)errors.push(file+' duplicate IDs');for(const m of s.matchAll(/href="#([^"]+)"/g))if(!ids.includes(m[1]))errors.push(file+' missing target '+m[1]);const tablets=(s.match(/<article class="tablet/g)||[]).length,clocks=(s.match(/<time class="clock/g)||[]).length;if(clocks<tablets)errors.push(file+' too few clocks');if(!D.includes('mockups/'+file)||!E.includes('mockups/'+file))errors.push(file+' not linked from both spines');results.push(file+': anchors valid; '+tablets+' tablet frames, '+clocks+' clocks');}
for(const f of ['driving.html','summary-recovery.html','remaining-screens.html'])if(!read('mockups/'+f).includes('text-underline-offset:5px'))errors.push(f+' missing Auto cue');
for(const t of ['Revision ownership and linked contexts','Role and context recovery','Explicit tracking-context changes','Accompanied-person imports and summary scope'])if(!E.includes('### '+t))errors.push('Missing rule '+t);
results.push('Auto underline and review-resolution sections present');
console.log(JSON.stringify({errors,results},null,2));if(errors.length)process.exitCode=1;
else fs.writeFileSync(path.join(__dirname,'final-verification.md'),'# Final reference checks\n\n2026-09-22. Static document/reference checks only.\n\n'+results.map(x=>'- '+x).join('\n')+'\n\nBrowser screenshot inspected: primary day driving header clock fits without shrinking stop focus; manual Auto remains un-underlined. Active Auto/gallery check recorded separately. Physical device, sensor and implemented interaction testing remain downstream.\n');
